### PR TITLE
fixed access check for non-administrators

### PR DESCRIPTION
**Pull request by nomennesc-io**
First off, thanks a bunch for the SAML implementation! I noticed however, non-administrator users ran into errors when trying to manage their domains. I'm not sure what you were trying to do with the get_domain_query() call, but I believe this fixes the issue.

### CODE REVIEW

**Comment by nomennesc-io** [comment]
the second commit also implements a workaround for https://github.com/thomasDOTde/PowerDNS-Admin/issues/6 (full SLO functionality would still remain on the wish-list, but at least this way you can make sure the SAML session will be ended on logout).

**Comment by thomasDOTwtf** [comment]
Hey,

thanks for your contribution and enhancements! I haven't even recognized that the whole standard users access permission check is broken since a long time. I've done a little optimization to it in a way that the database will do the work for us.

Second:
For SAML logout I implemented the standard SAML logout process using the url inside the SAML metadata. Since my SAML idp isn't able to process unsigned logout request could you give it a try.
I've made the final url which will be redirected to after SAML logout configurable. It can also be configured if SAML logout should be performed.

Could you review the changes I've made and give me some feedback on the code and the SAML logout test?

Thanks
Thomas

**Comment by nomennesc-io** [comment]
Great, this is starting to really look like actual SLO :)
While testing I noticed an incorrect parameter name, which the last commit fixes. 
I've also patched the sls mechanism to respect the redirect url. If I understood things correctly, after logout is called, a request is sent to the IdP, which sends a response that is handled by saml_logout, calling process_slo. 
saml_logout hopes to get a url from process_slo, which should be the case for SAMLRequests, but not in this case of SAMLResponse. Hence another check whether we have a redirect url configured locally.

Finally, it might be worth documenting that a signed logout response from the IdP is mandatory, which for simplesamlphp users like me means adding 'sign.logout' => TRUE to the metadata.

**Comment by thomasDOTwtf** [comment]
I would merge the pr and implement signed requests in a separate pr.
I've already tested it locally with some problems of Case-Sensitivity for ADFS 3.
That was already addressed in the utils library.
[https://github.com/thomasDOTde/PowerDNS-Admin/blob/b55833bd2a439c21c202eb4d409bbe0dbc8e696f/app/lib/utils.py#L206](url)

**Comment by nomennesc-io** [comment]
Thank you!

**Pull request merged**
